In [ ]:
## https://www.rdkit.org/docs/GettingStartedInPython.html#:~:text=The%20RDKit%20can%20generate%20conformers,and%20a%20set%20of%20rules.

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
get_path = 'drive/MyDrive/Skip-GNN/'

### RDKit

In [ ]:
!pip install rdkit-pypi

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: rdkit-pypi in /usr/local/lib/python3.7/dist-packages (2022.3.4)
Requirement already satisfied: Pillow in /usr/local/lib/python3.7/dist-packages (from rdkit-pypi) (7.1.2)
Requirement already satisfied: numpy in /usr/local/lib/python3.7/dist-packages (from rdkit-pypi) (1.21.6)

In [ ]:
from rdkit import Chem

In [ ]:
import pandas as pd
import numpy as np
import multiprocessing
import logging

In [ ]:
import seaborn as sb
sb.set()
from matplotlib import pyplot
import matplotlib.pyplot as plt
%matplotlib inline

### Process Protein Sequences

In [ ]:
import pandas as pd

In [ ]:
## Read dataset
df = pd.read_csv(get_path + 'data/all_sequences.txt', sep='\t', header=None)
df.columns=['id', 'seq']
df = df.rename(columns={'id': 'Protein1_ID'})
df

      Protein1_ID                                                seq
0          P03428  MERIKELRNLMSQSRTREILTKTTVDHMAIIKKYTSGRQEKNPALR...
1          P03431  MDVNPTLLFLKVPAQNAISTTFPYTGDPPYSHGTGTGYTMDTVNRT...
2          P03433  MEDFVRQCFNPMIVELAEKTMKEYGEDLKIETNKFAAICTHLEVCF...
3          P03452  MKANLLVLLCALAAADADTICIGYHANNSTDTVDTVLEKNVTVTHS...
4          P03466  MASQGTKRSYEQMETDGERQNATEIRASVGKMIGGIGRFYIQMCTE...
...           ...                                                ...
15728      I6T1Z7  MERIKELRNLMSQSRTREILTKTTVDHMAIIKKYTSGRQEKNPSLR...
15729      Q67157  MSLLTEVETYVLSIVPSGPLKAEIAQRLEDVFAGKNTDLEALMEWL...
15730      I6TAH8  MASQGTKRSYEQMETDGERQNATEIRASVGKMIDGIGRFYIQMCTE...
15731      Q02600  MDSNTVSSFQDILLRMSKMQLGSSSEDLNGMITQFESLKLYRDSLG...
15732      I6TAI3  MEQEQDTPWTQSTEHINIQKKGSGQQTRKLERPNLTQLMDHYLRIM...

[15733 rows x 2 columns]

In [ ]:
## Count sequence length
new_pl = pd.read_csv('/drive/MyDrive/Structure_PPI_GNN/protein_list_filtered.csv')
new_pl

In [ ]:
protein_list = pd.read_csv('drive/MyDrive/Skip-GNN/data/IAV/protein_list.csv')
protein_list = protein_list.drop(columns=['Unnamed: 0'])
protein_list ## 15685 rows

      Protein1_ID
0          P03428
1          P03431
2          P03433
3          P03452
4          P03466
...           ...
15680      Q6NUS8
15681      P12018
15682      Q96IU2
15683      Q6PEW1
15684      P0CG32

[15685 rows x 1 columns]

In [ ]:
## Exclude sequences not in protein list
merge_df = pd.merge(df, protein_list, on=['Protein1_ID'])
merge_df

      Protein1_ID                                                seq
0          P03428  MERIKELRNLMSQSRTREILTKTTVDHMAIIKKYTSGRQEKNPALR...
1          P03431  MDVNPTLLFLKVPAQNAISTTFPYTGDPPYSHGTGTGYTMDTVNRT...
2          P03433  MEDFVRQCFNPMIVELAEKTMKEYGEDLKIETNKFAAICTHLEVCF...
3          P03452  MKANLLVLLCALAAADADTICIGYHANNSTDTVDTVLEKNVTVTHS...
4          P03466  MASQGTKRSYEQMETDGERQNATEIRASVGKMIGGIGRFYIQMCTE...
...           ...                                                ...
15680      I6T1Z7  MERIKELRNLMSQSRTREILTKTTVDHMAIIKKYTSGRQEKNPSLR...
15681      Q67157  MSLLTEVETYVLSIVPSGPLKAEIAQRLEDVFAGKNTDLEALMEWL...
15682      I6TAH8  MASQGTKRSYEQMETDGERQNATEIRASVGKMIDGIGRFYIQMCTE...
15683      Q02600  MDSNTVSSFQDILLRMSKMQLGSSSEDLNGMITQFESLKLYRDSLG...
15684      I6TAI3  MEQEQDTPWTQSTEHINIQKKGSGQQTRKLERPNLTQLMDHYLRIM...

[15685 rows x 2 columns]

In [ ]:
merge_df.to_csv('drive/MyDrive/Skip-GNN/data/new_all_sequences.txt', index=False, sep='\t', header=None)

In [ ]:
## Convert to fasta
!pip install biopython

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting biopython
  Downloading biopython-1.79-cp37-cp37m-manylinux_2_5_x86_64.manylinux1_x86_64.whl (2.3 MB)
     |â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 2.3 MB 16.4 MB/s
Requirement already satisfied: numpy in /usr/local/lib/python3.7/dist-packages (from biopython) (1.21.6)
Installing collected packages: biopython
Successfully installed biopython-1.79

In [ ]:
from Bio import SeqIO
SeqIO.convert('drive/MyDrive/Skip-GNN/data/new_all_sequences.txt', 'tab', 'drive/MyDrive/Skip-GNN/data/all_sequences.FASTA', 'fasta')

15685